# Generated by Django 5.2.4 on 2026-01-28 19:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_event_tags_alter_academicinfo_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hosts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, default=list, max_length=30),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/home/samtheradiant/PycharmProjects/ACM-CUI-Web/backend/media/events/default.png",
                null=True,
                upload_to="events/",
            ),
        ),
    ]
