# Generated by Django 5.2.4 on 2026-02-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_eventregistration_eventparticipant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rolepreferences",
            name="weekly_availability",
            field=models.CharField(
                blank=True,
                help_text="Available hours per week for ACM activities",
                max_length=100,
                null=True,
            ),
        ),
    ]
