# Generated by Django 5.2.4 on 2026-02-06 19:59

import api.models.event
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_eventregistration_eventparticipant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/home/hafeez/Desktop/deployment/backend/media/events/default.png",
                null=True,
                upload_to="events/",
            ),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/home/hafeez/Desktop/deployment/backend/media/events/default.png",
                null=True,
                upload_to=api.models.event.event_image_upload_path,
            ),
        ),
    ]
