# Generated by Django 5.2.4 on 2026-02-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_event_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="image",
            field=models.CharField(max_length=255),
        ),
    ]
