# Generated by Django 5.2.4 on 2026-02-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_bill_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_pic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
