# Generated by Django 5.2.4 on 2026-02-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_student_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogimage",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="inlineimage",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
