# Generated by Django 5.2.4 on 2026-02-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_event_image_alter_eventimage_image"),
        ("api", "0012_alter_blogimage_image_alter_inlineimage_image"),
    ]

    operations = []
