# Generated by Django 5.2.4 on 2026-02-12 14:21

import api.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_merge_20260212_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentapplication",
            name="comment",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/home/samtheradiant/PycharmProjects/ACM-CUI-Web/backend/media/events/default.png",
                null=True,
                upload_to=api.models.event.event_image_upload_path,
            ),
        ),
    ]
