# Generated by Django 5.2.4 on 2026-07-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20260208_1715'),
        ('api', '0014_recruitmentapplication_comment_alter_event_image_and_more'),
    ]

    operations = [
    ]
