# Generated by Django 5.2.4 on 2026-07-16 06:47

import api.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_merge_20260709_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicinfo",
            name="program",
            field=models.CharField(
                choices=[
                    ("BSCS", "Bscs"),
                    ("BSSE", "Bsse"),
                    ("BSAI", "Bsai"),
                    ("BSEE", "Bsee"),
                    ("BSCE", "Bsce"),
                    ("BSME", "Bsme"),
                    ("BSCVE", "Bscve"),
                    ("BBA", "Bba"),
                    ("HUM", "Hum"),
                    ("BS_MATH", "Bs Math"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="E:\\ACM_WEBSITE\\ACM-CUI-Web\\backend\\media/events/default.png",
                null=True,
                upload_to=api.models.event.event_image_upload_path,
            ),
        ),
    ]
