# Generated by Django 5.2.4 on 2026-07-17 04:12

import api.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_birthday_alter_academicinfo_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='second_preference_club_label',
            field=models.CharField(blank=True, choices=[('CODEHUB', 'Codehub'), ('GRAPHICS', 'Graphics'), ('SOCIAL_MEDIA_MARKETING', 'Social Media Marketing'), ('MEDIA', 'Media'), ('DECOR', 'Decor'), ('EVENTS_LOGISTICS', 'Events Logistics')], help_text='The club/role that the 2nd preference comment is associated with.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='second_preference_comment',
            field=models.TextField(blank=True, default='', help_text='Interview comment specifically for the 2nd preference club.', null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='selected_preference',
            field=models.CharField(choices=[('FIRST_PREFERENCE', 'First Preference'), ('SECOND_PREFERENCE', 'Second Preference')], default='FIRST_PREFERENCE', help_text='Whether the student was selected for their 1st or 2nd preference.', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, default='D:\\Coding\\ACM\\ACM Website\\backend\\media/events/default.png', null=True, upload_to=api.models.event.event_image_upload_path),
        ),
    ]
