# Generated by Django 5.2.4 on 2026-07-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_academicinfo_program_alter_eventimage_image'),
        ('api', '0017_add_second_preference_fields'),
    ]

    operations = [
    ]
